### ISSUE TITLE
gatsby-starter-i18next is not working

### ISSUE THREAD

**Issue by ikhudo** [hupe1980/gatsby-i18n#1]
Is there any working with gatsby 2 example/starter?

**Comment by ferni** [comment]
@ikhudo I've seen you've forked the project, have you managed to fix this?

**Comment by ikhudo** [comment]
@ferni I've fixed the package, try to fork my version.
working version is in this repo https://github.com/ikhudo/gatsby-i18n-plugin

**Comment by hupe1980** [comment]
@ferni I've fixed it, too....
