### ISSUE TITLE
plugin not working if used in combination with gatsby-plugin-layout

### ISSUE THREAD

**Issue by MikeBroders** [hupe1980/gatsby-i18n#12]
hey,

i'm using the gatsby-plugin-layout plugin and facing some issues...
it seems that with this setup the initial locale-data are not getting passed to the i18n setup.

i'm wrapping the centralized "layout" component with the useI18next()(Layout) HOC 

usually to make your plugin work i have to pass a data-object from a page-query for every page that want's to use your plugin but in this scenario i wanted to have only the "layout" component be wrapped with the HOC and provides down the i18n instance because the page will not be reloaded at navigation.

i managed this by adding the initial page data for the "layout" component in the gatsby-node.js with the onCreatePage function.

your plugin is looking for the locales props.data-object of the graphql page-query result but with my workaround there is only the props.pageContext object available to pass the locales data to the component.

would it make sense to check props.data and props.pageContext for the locales object?

or do you see any other way to come around this?

thanks in advance 
mike

setup:

Gatsby 2
gatsby-plugin-layout
@wapps/gatsby-plugin-i18next

**Comment by MikeBroders** [comment]
maybe also a forced rerender would be necessary if the page is not reloading on navigation

**Comment by hupe1980** [comment]
I have not understood your issue yet. Do you have a minimal reproduction repo?

**Comment by MikeBroders** [comment]
hey :)

it’s about the special setup with the gatsby-plugin-layout where the laytout is not reloaded on navigation and i want to wrap the laypot-componetnt with the withI18next HOC…

if i find some time i'll try to setup a repo

mike

**Comment by MikeBroders** [comment]
hey, i could solve this issue by unfortunately not using your plugin. 
now i have a custom i18n instance and create the HOC by myself. to get the locale-data into the layout i pass them in the onCreatePage loop in gatsby-node.js and render a page for every used locale.

on the other hand your plugin is a good solution for every 'common' gatsby setup.

thanks & cheers
mike
